name: Auto Scan

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    concurrency:
      group: auto

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - name: Start Scan
        run: |
          npm install && npm run auto
      - name: Publish Result
        if: ${{ success() }}
        uses: EndBug/add-and-commit@v9
        with:
          add: '["./result --force"]'
          default_author: github_actions
          fetch: false
          tag_push: "--force"
          message: "Update Subdomains"
